{{- if .Values.ingress.enabled -}}
{{- $servicePort := .Values.service.port -}}
{{- $basePath := .Values.basePath -}}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ template "jaeger-all-in-one.name" . }}
  labels:
    {{- include "jaeger-all-in-one.labels" . | nindent 4 }}
    app.kubernetes.io/component: all-in-one
  {{- if .Values.ingress.annotations }}
  annotations:
{{ toYaml .Values.ingress.annotations | indent 4 }}
  {{- end }}
spec:
  rules:
    {{- range $host := .Values.ingress.hosts }}
    - host: {{ $host }}
      http:
        paths:
          - path: {{ $basePath }}
            backend:
              serviceName: {{ template "jaeger-all-in-one.name" $ }}-query
              servicePort: {{ $servicePort }}
    {{- end -}}
  {{- if .Values.ingress.tls }}
  tls:
{{ toYaml .Values.ingress.tls | indent 4 }}
  {{- end -}}
{{- end -}}
